#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Aerospike cluster size
graph_vlabel Nodes
aeroclustersize.label Cluster
graph_category Aerospike
EOM
        exit 0;;
esac

echo -n "aeroclustersize.value "
clinfo | grep statistics -A 2 | tr ";" "\n" | grep cluster_size | tr '=' ' ' | awk '{print $2}'
