#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Cassandra columnfamilies data
org_apache_cassandra_db_usertable_columnfamilies_data_readcount.type COUNTER
org_apache_cassandra_db_usertable_columnfamilies_data_readcount.label Read
org_apache_cassandra_db_usertable_columnfamilies_data_writecount.type COUNTER
org_apache_cassandra_db_usertable_columnfamilies_data_writecount.label Write
graph_category Cassandra
EOM
        exit 0;;
esac

java -jar /usr/share/munin/plugins/jmx2munin.jar -url service:jmx:rmi:///jndi/rmi://localhost:7199/jmxrmi -query "org.apache.cassandra.*:*" -attribute org_apache_cassandra_db_usertable_columnfamilies_data_readcount
java -jar /usr/share/munin/plugins/jmx2munin.jar -url service:jmx:rmi:///jndi/rmi://localhost:7199/jmxrmi -query "org.apache.cassandra.*:*" -attribute org_apache_cassandra_db_usertable_columnfamilies_data_writecount